### PR TITLE
poz

### PR DESCRIPTION
**Pull request by imnotpoz**
poz

### CODE REVIEW

**Comment by vdawg-git** [comment]
xDDDDDD

**Comment by imnotpoz** [comment]
thanks dawg

**Comment by NotAShelf** [comment]
dawg

**Comment by imnotpoz** [comment]
daog

**Comment by NotAShelf** [comment]
I still think this PR is what made ZenVer truly the best versioning spec out there

**Comment by imnotpoz** [comment]
aside from pozver of course

**Pull request merged**
